# Compilacion del proyecto
FROM node:current-alpine3.11 as builder
WORKDIR /app
COPY . ./
RUN npm install && npm run build

# Empaquetado de final del proyecto
FROM node:current-alpine3.11
WORKDIR /app
COPY package.json .env ./
COPY --from=builder /app/dist ./dist
RUN npm install --production
EXPOSE 4000
CMD ["npm","start"]